#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(optparse)
  library(PGEcore)
})

opts <- list(
  make_option(
    c("-i", "--coi_table"),
    help = "TSV containing coi calls, with the columns: specimen_name, coi ",
    type = "character",
    default = NULL,
    callback = function(opt, flag_string, value, parser, ...) {
      if (!file.exists(value)) {
        stop(paste0(value, " does not exist"), call. = FALSE)
      }
      value
    }
  ),
  make_option(
    c("-o", "--output"),
    help = "Output file name. Default: %default",
    type = "character",
    default = "coi_distribution.tsv"
  )
)

args <- parse_args(OptionParser(option_list = opts))
if (is.null(args$coi_table)) {
  stop("Missing required arguments: --coi_table", call. = FALSE)
}

invisible(count_samples_by_coi(coi_table = args$coi_table, output = args$output))
