#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(optparse)
  library(PGEcore)
})

opts <- list(
  make_option(
    c("--aa_calls"),
    help = "AA calls TSV (specimen_name, gene_id, aa_position, aa). See vignette input-formats.",
    type = "character",
    default = NULL,
    callback = function(opt, flag_string, value, parser, ...) {
      if (!file.exists(value)) {
        stop(paste0(value, " does not exist"), call. = FALSE)
      }
      value
    }
  ),
  make_option(
    c("--allele_table"),
    help = "Allele table TSV (specimen_name, target_name, seq). See vignette input-formats.",
    type = "character",
    default = NULL,
    callback = function(opt, flag_string, value, parser, ...) {
      if (!file.exists(value)) {
        stop(paste0(value, " does not exist"), call. = FALSE)
      }
      value
    }
  ),
  make_option(
    c("-o", "--output"),
    help = "Prevalence TSV output. Default: %default",
    type = "character",
    default = "prevalence.tsv"
  )
)

args <- parse_args(OptionParser(option_list = opts))
input_data_args <- c("aa_calls", "allele_table")
absent_data_args <- setdiff(input_data_args, names(args))
if (length(absent_data_args) != 1) {
  stop(
    "One and only one of the args --aa_calls and --allele_table should be ",
    "provided.",
    call. = FALSE
  )
}

invisible(
  estimate_allele_prevalence_naive(
    aa_calls = args$aa_calls,
    allele_table = args$allele_table,
    output = args$output
  )
)
