#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(optparse)
  library(PGEcore)
})

opts <- list(
  make_option(
    c("--aa_calls"),
    help = "AA calls TSV (specimen_name, gene_id, aa_position, aa, reads). See vignette input-formats.",
    type = "character",
    default = NULL,
    callback = function(opt, flag_string, value, parser, ...) {
      if (!file.exists(value)) {
        stop(paste0(value, " does not exist"), call. = FALSE)
      }
      value
    }
  ),
  make_option(
    c("--allele_table"),
    help = "Allele table TSV (specimen_name, target_name, seq, reads). See vignette input-formats.",
    type = "character",
    default = NULL,
    callback = function(opt, flag_string, value, parser, ...) {
      if (!file.exists(value)) {
        stop(paste0(value, " does not exist"), call. = FALSE)
      }
      value
    }
  ),
  make_option(
    c("-m", "--method"),
    help = paste0(
      "Method to use for estimating allele frequency. Options are: ",
      "read_count_prop, presence_absence. Default: %default"
    ),
    type = "character",
    default = "presence_absence",
    callback = function(opt, flag_string, value, parser, ...) {
      if (!value %in% c("read_count_prop", "presence_absence")) {
        stop(paste0(value, " is not a valid method"), call. = FALSE)
      }
      value
    }
  ),
  make_option(
    c("-o", "--output"),
    help = "Allele frequency TSV output. Default: %default",
    type = "character",
    default = "allele_frequency.tsv"
  )
)

args <- parse_args(OptionParser(option_list = opts))
input_data_args <- c("aa_calls", "allele_table")
absent_data_args <- setdiff(input_data_args, names(args))
if (length(absent_data_args) != 1) {
  stop(
    "One and only one of the args --aa_calls and --allele_table should be ",
    "provided.",
    call. = FALSE
  )
}

invisible(
  estimate_allele_frequency_naive(
    aa_calls = args$aa_calls,
    allele_table = args$allele_table,
    method = args$method,
    output = args$output
  )
)
