#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(optparse)
  library(PGEcore)
})

opts <- list(
  make_option(
    "--snp_table_in",
    help = paste(
      "TSV containing at least the columns: specimen_name, target_name,",
      "chrom, pos, snp_name, ref_base, seq_base, reads, is_biallelic"
    )
  ),
  make_option(
    "--snp_table_out",
    help = "the output filename path for the output filtered file"
  ),
  make_option(
    "--mindist_between_snps",
    type = "integer",
    default = 10000,
    help = "the minimum distance between SNPs to consider them 'independent'. Default: %default"
  ),
  make_option(
    "--select_target_names",
    help = "only process these targets"
  ),
  make_option(
    "--select_specimen_names",
    help = "only process these samples"
  ),
  make_option(
    "--overwrite",
    help = "overwrite the output fnp if it already exists. Default: %default",
    action = "store_true",
    default = FALSE,
    type = "logical"
  ),
  make_option(
    "--only_biallelic",
    help = "filter to only biallelic SNPs too. Default: %default",
    action = "store_true",
    default = FALSE,
    type = "logical"
  ),
  make_option(
    "--only_informative",
    help = "filter off SNPs with no variation. Default: %default",
    action = "store_true",
    default = FALSE,
    type = "logical"
  )
)

arg <- parse_args(OptionParser(option_list = opts))
if (is.null(arg$snp_table_in) || is.null(arg$snp_table_out)) {
  stop(
    "Missing required arguments: --snp_table_in and --snp_table_out",
    call. = FALSE
  )
}

invisible(
  filter_to_highest_diversity_independent_snp_call(
    snp_table_in = arg$snp_table_in,
    snp_table_out = arg$snp_table_out,
    mindist_between_snps = arg$mindist_between_snps,
    select_target_names = arg$select_target_names,
    select_specimen_names = arg$select_specimen_names,
    overwrite = isTRUE(arg$overwrite),
    only_biallelic = isTRUE(arg$only_biallelic),
    only_informative = isTRUE(arg$only_informative)
  )
)
