#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(optparse)
  library(PGEcore)
})

opts <- list(
  make_option(
    "--allele_table",
    help = paste0(
      "Allele table TSV (specimen_name, target_name, seq). ",
      "See vignette input-formats."
    ),
    type = "character",
    default = NULL
  ),
  make_option(
    "--subset_targets",
    help = "A logical to indicate whether the matrix should be subset by user-supplied target_name",
    type = "logical",
    default = FALSE
  ),
  make_option(
    "--target_groups",
    help = paste0(
      "Optional groups TSV (group_id, target_name) when --subset_targets TRUE."
    ),
    type = "character",
    default = NULL
  ),
  make_option(
    "--max_size",
    help = paste0(
      "Single population-COI value (e.g. '2')",
      "Cutoff to not run Malaria EM due to time constraints",
      "Default is max size of 8"
    ),
    type = "character",
    default = "8"
  ),
  make_option(
    "--test_size",
    help = paste0(
      "Single COI value (e.g. '2'), or 'min' to default to the minimum allowed set size",
      "Default is 'min'"
    ),
    type = "character",
    default = "min"
  ),
  make_option(
    "--freq_output",
    help = "Output genotype-frequency TSV (gt_id, target_name, seq, freq, freq_se).",
    type = "character",
    default = "gt_freq_summary_all.tsv"
  ),
  make_option(
    "--phase_output",
    help = "Output phasing TSV (specimen_name, target_name, seq, gt_id, posterior_est, phase_id).",
    type = "character",
    default = "gt_phase_summary_all.tsv"
  )
)

arg <- parse_args(OptionParser(option_list = opts))
if (is.null(arg$allele_table)) {
  stop("Missing required arguments: allele_table", call. = FALSE)
}

invisible(
  malariaem_wrapper(
    allele_table = arg$allele_table,
    subset_targets = arg$subset_targets,
    target_groups = arg$target_groups,
    max_size = arg$max_size,
    test_size = arg$test_size,
    freq_output = arg$freq_output,
    phase_output = arg$phase_output
  )
)
