#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(optparse)
  library(PGEcore)
})

opts <- list(
  make_option(
    "--aa_calls",
    type = "character",
    help = paste0(
      "AA calls TSV (specimen_name, gene_id, aa_position, ref_aa, aa). ",
      "See vignette input-formats."
    )
  ),
  make_option(
    "--loci_groups",
    type = "character",
    help = paste0(
      "Loci groups TSV (group_id, gene_id, aa_position). ",
      "See vignette input-formats."
    )
  ),
  make_option(
    "--mlaf_output",
    type = "character",
    help = paste0(
      "Output MLAF TSV (group_id, variant, freq)."
    )
  ),
  make_option(
    "--aa_sample_occurence_cut_off",
    type = "integer",
    default = 0,
    help = paste0(
      "Amino acid calls must occur in more than this number of samples ",
      "to be included in final input data"
    )
  )
)

arg <- parse_args(OptionParser(option_list = opts))
if (is.null(arg$aa_calls) || is.null(arg$loci_groups) ||
    is.null(arg$mlaf_output)) {
  stop(
    "Missing required arguments: --aa_calls, --loci_groups, --mlaf_output",
    call. = FALSE
  )
}

invisible(
  MultiLociBiallelicModel_wrapper(
    aa_calls = arg$aa_calls,
    loci_groups = arg$loci_groups,
    mlaf_output = arg$mlaf_output,
    aa_sample_occurence_cut_off = arg$aa_sample_occurence_cut_off
  )
)
