#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(optparse)
  library(PGEcore)
})

opts <- list(
  make_option(
    "--aa_calls",
    type = "character",
    help = paste0(
      "Path to a TSV file containing amino acid calls, with the columns: specimen_name, ",
      "gene, pos, reads, aa"
    )
  ),
  make_option(
    "--loci_groups",
    type = "character",
    help = paste0(
      "Path to a TSV file containing loci group definitions, with the ",
      "columns: group_id, gene_id, aa_position"
    )
  ),
  make_option(
    "--output",
    type = "character",
    help = paste0(
      "Path to write an output TSV file containing prevalence and frequency estimates ",
      "for all variants in the data"
    )
  )
)

args <- parse_args(OptionParser(option_list = opts))

missing <- character()
if (is.null(args$aa_calls)) {
  missing <- c(missing, "--aa_calls")
}
if (is.null(args$loci_groups)) {
  missing <- c(missing, "--loci_groups")
}
if (is.null(args$output)) {
  missing <- c(missing, "--output")
}
if (length(missing) > 0) {
  stop(
    "Missing the following arguments: ",
    paste(missing, collapse = ", "),
    call. = FALSE
  )
}

invisible(
  multilocus_prevfreq_naive_variantstring(
    aa_calls = args$aa_calls,
    loci_groups = args$loci_groups,
    output = args$output
  )
)
