#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(optparse)
  library(PGEcore)
})

opts <- list(
  make_option(
    c("-i", "--mlaf_input"),
    help = paste(
      "TSV containing multi-locus allele frequency data with columns:",
      "group_id, variant, freq. Variant column is in STAVE format."
    ),
    type = "character",
    default = NULL,
    callback = function(opt, flag_string, value, parser, ...) {
      if (!file.exists(value)) {
        stop(paste0(value, " does not exist"), call. = FALSE)
      }
      value
    }
  ),
  make_option(
    c("-o", "--output"),
    help = "Output file name. Default: %default",
    type = "character",
    default = "single_locus_allele_frequencies.tsv"
  )
)

args <- parse_args(OptionParser(option_list = opts))
if (is.null(args$mlaf_input)) {
  stop("Missing required arguments: --mlaf_input", call. = FALSE)
}

invisible(
  slaf_from_stave_mlaf(mlaf_input = args$mlaf_input, output = args$output)
)
