#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(optparse)
  library(PGEcore)
})

opts <- list(
  make_option(
    "--mhaps_slaf",
    help = paste(
      "TSV containing the columns: target_name, seq, freq, sample_total.",
      "The target_name and seq columns should match up with the columns in",
      "loci_of_interest_per_microhaps"
    )
  ),
  make_option(
    "--loci_of_interest_per_microhaps",
    help = paste(
      "TSV containing the columns: target_name, seq, gene_id, aa_position, aa.",
      "The target_name and seq columns should match up with the columns in",
      "mhaps_slaf"
    )
  ),
  make_option(
    "--slaf_output",
    help = paste(
      "the output for the single locus allele frequency, will collapse",
      "frequencies across overlapping targets"
    )
  ),
  make_option(
    "--per_target_slaf_output",
    help = paste(
      "optional output for the single lcous allele frequency calculated",
      "per target"
    )
  )
)

args <- parse_args(OptionParser(option_list = opts))
if (
  is.null(args$mhaps_slaf) ||
    is.null(args$loci_of_interest_per_microhaps) ||
    is.null(args$slaf_output)
) {
  stop(
    paste(
      "Missing required arguments: --mhaps_slaf,",
      "--loci_of_interest_per_microhaps, and --slaf_output"
    ),
    call. = FALSE
  )
}

invisible(
  slaf_from_mhaps_freqs(
    mhaps_slaf = args$mhaps_slaf,
    loci_of_interest_per_microhaps = args$loci_of_interest_per_microhaps,
    slaf_output = args$slaf_output,
    per_target_slaf_output = args$per_target_slaf_output
  )
)
